version: "3.8"
services:
  config-server:
    image: "config-server"
    container_name: "config-server"
    environment:
      - THC_PATH=/actuator/health
      - THC_PORT=9095
    ports:
      - "9095:9095"
    healthcheck:
      test: [ "CMD", "/cnb/process/health-check" ]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 20s

  review-service:
    image: "review-service"
    container_name: "review-service"
    depends_on:
      postgres-reviews:
        condition: service_healthy
      config-server:
        condition: service_healthy
    ports:
      - "9093:9093"
    environment:
      - CONFIGSERVER_IMPORT=configserver:${CONFIG_SERVER_URL}
      - SPRING_CLOUD_CONFIG_FAIL_FAST=true
      - SPRING_PROFILES_ACTIVE=prod
      - DB_USER=${REVIEW_DB_USER}
      - DB_PASSWORD=${REVIEW_DB_PASSWORD}
      - DB_URL=${REVIEW_DB_URL}


  postgres-reviews:
    image: "postgres:16.1"
    container_name: "postgres-reviews"
    ports:
      - "5433:5433"
    environment:
      - POSTGRES_USER=${REVIEW_DB_USER}
      - POSTGRES_PASSWORD=${REVIEW_DB_PASSWORD}
      - POSTGRES_DB=review_service_db
      - PGPORT=5433
    volumes:
      - db-reviews:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "review_service_db" ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s

volumes:
  db-reviews:
    driver: local